<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3d2143d5-f04d-4ab5-b1db-d61f5bb57076</elementGuidId>
    <imagePath></imagePath>
    <name>link_InvestmentFinder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[4]/div[1]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__content"]:nth-child(4) [class="fd-megamenu--desktop__subject"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/products/investmentfinder/') and equals(@text,'Investment Finder
            
            Search through our products using a wide range of filters and criteria.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(4) &gt; .fd-megamenu--desktop__content-container &gt; .fd-megamenu--desktop__subjects &gt; a:nth-child(3)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/products/investmentfinder/</value>
        <webElementGuid>d741da60-8342-4b7e-832b-a0efd6e4eb51</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Investment Finder
        
        Search through our products using a wide range of filters and criteria.</value>
        <webElementGuid>d741da60-8342-4b7e-832b-a0efd6e4eb51</webElementGuid>
    </webElementProperties>
</WebElementEntity>