<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>802e562d-c1ab-4d01-813e-670e973a53f5</elementGuidId>
    <imagePath></imagePath>
    <name>link_AddRecurringClaims</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[7]/div[8]/div[3]/div[1]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#form-printing-actions li:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/registrations/1/recurring_claims/new') and equals(@text,'Add Recurring Claims')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Add Recurring Claims"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/registrations/1/recurring_claims/new</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add Recurring Claims</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
</WebElementEntity>