<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>15f925fb-d64d-40c1-b166-e3cc0a4285b3</elementGuidId>
    <imagePath></imagePath>
    <name>link_SubmitSmartForms</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/table[1]/tbody[1]/tr[1]/td[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>tr:nth-child(1) [class="btn\ btn-mini\ btn-warning\ open-in-modal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/smart_forms/schedules/new?aac_region%5B%5D=HVTC+Sydney&amp;aac_region%5B%5D=Hunter+New+England&amp;aac_region%5B%5D=Illawarra+South+Coast&amp;action=index&amp;claim_status%5B%5D=6&amp;claim_status%5B%5D=9&amp;controller=smart_forms%2Fschedules&amp;due_at%5Bfrom%5D={{date_time}}&amp;due_at%5Bto%5D={{date_time}}&amp;smart_form_lodgement_type=email&amp;supercharged_incentive=false')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Submit Smart Forms"i] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/smart_forms/schedules/new?aac_region%5B%5D=HVTC+Sydney&amp;aac_region%5B%5D=Hunter+New+England&amp;aac_region%5B%5D=Illawarra+South+Coast&amp;action=index&amp;claim_status%5B%5D=6&amp;claim_status%5B%5D=9&amp;controller=smart_forms%2Fschedules&amp;due_at%5Bfrom%5D={{date_time}}&amp;due_at%5Bto%5D={{date_time}}&amp;smart_form_lodgement_type=email&amp;supercharged_incentive=false</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
</WebElementEntity>