<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d7f577e8-46ad-4be5-9f08-92aa4bef04ed</elementGuidId>
    <imagePath></imagePath>
    <name>link_SmartFormApplications</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[7]/div[1]/div[2]/ul[1]/li[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="well"]:nth-child(2) &gt; [class="nav\ nav-list"] &gt; li:nth-child(6) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/smart_forms/application_forms') and equals(@text,'Smart Form Applications')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name=" Smart Form Applications"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/smart_forms/application_forms</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Smart Form Applications</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
</WebElementEntity>