<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9295ee00-a3cf-4022-acee-4fff73b617d0</elementGuidId>
    <imagePath></imagePath>
    <name>link_RetirementCalculator</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[4]/div[1]/div[1]/a[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__content"]:nth-child(4) [class="fd-megamenu--desktop__subject"]:nth-child(6)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/retirementcalculator/') and equals(@text,'Retirement calculator
            
            Discover how much you need to retire — and whether you're heading in the right direction.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(4) &gt; .fd-megamenu--desktop__content-container &gt; .fd-megamenu--desktop__subjects &gt; a:nth-child(6)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/retirementcalculator/</value>
        <webElementGuid>d741da60-8342-4b7e-832b-a0efd6e4eb51</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Retirement calculator
        
        Discover how much you need to retire — and whether you're heading in the right direction.</value>
        <webElementGuid>d741da60-8342-4b7e-832b-a0efd6e4eb51</webElementGuid>
    </webElementProperties>
</WebElementEntity>