<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e8e4e9e7-74fb-4a9c-81b4-eaeb1a8e051f</elementGuidId>
    <imagePath></imagePath>
    <name>link_BulkReAssign</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[7]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu\ bulk-actions"] &gt; li:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/bulk_actions/smart_forms/reassign/new') and equals(@text,'Bulk Re-Assign')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name=" Bulk Re-Assign"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/bulk_actions/smart_forms/reassign/new</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Bulk Re-Assign</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
</WebElementEntity>