<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c76a22e9-687f-4f55-98b7-fab123f805f7</elementGuidId>
    <imagePath></imagePath>
    <name>select_Type</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/form[1]/div[2]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#recurring_claim_claim_type_code</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'recurring_claim_claim_type_code') and equals(@name,'recurring_claim[claim_type_code]')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="* Type"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>recurring_claim_claim_type_code</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>recurring_claim[claim_type_code]</value>
        <webElementGuid>73a53014-7d36-461f-916e-42bc797dc161</webElementGuid>
    </webElementProperties>
</WebElementEntity>