<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>013d03b6-12d7-4fdd-ad0a-0d958a2ffa67</elementGuidId>
    <imagePath></imagePath>
    <name>div_HomepageRow</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="container\ \ fd-new-backgroundscontainer--pageWidth\ white"] &gt; [class="row\ fd-new-backgroundscontainer--row\ \ \ \ bg-padding-top-20\ bg-no-padding-bottom"] &gt; [class="flex-column\ background-padding\ col-12\ col-lg-4\ \ \ \ \ "]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.row &gt; div:nth-child(2) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>