<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b1982e7-f89b-4906-a0b1-b40668181ab9</elementGuidId>
    <imagePath></imagePath>
    <name>image_Icon</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="link-with-icon--content-item\ col-12\ col-lg-4\ \ left-aligned"]:nth-child(1) &gt; [class="link-with-icon--content-item--icon"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.link-with-icon--content-item--icon &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>