<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8b6207e0-de17-4cf9-a5ac-b23f03f205c5</elementGuidId>
    <imagePath></imagePath>
    <name>link_Insights</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/menu[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__section\ fd-megamenu--desktop__section--hover"] &gt; [class="fd-megamenu--desktop__section-button\ fd-megamenu--desktop__section-link\a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Insights')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Insights"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>d741da60-8342-4b7e-832b-a0efd6e4eb51</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Insights</value>
        <webElementGuid>d741da60-8342-4b7e-832b-a0efd6e4eb51</webElementGuid>
    </webElementProperties>
</WebElementEntity>